### ISSUE TITLE
Error loading trackeRapp

### ISSUE THREAD

**Issue by handrigg** [trackerproject/trackeRapp#50]
trackeR is a great package, thanks for the contribution. I only learned of the corresponding interface for it just now. However, I can't get it to load. I get the following error: 

 Error in : shinyjs: extendShinyjs: `functions` argument must be provided. See the documentation for `?extendShinyjs` for more details.

Any suggestions on how to fix this?

**Comment by ikosmidis** [comment]
Thanks for the report. This must be because of an update in one of the dependencies. Will traceback and fix asap.

**Comment by ikosmidis** [comment]
This should now be fixed. It should appear in CRAN in the next few weeks, after I take care of some other issues. In the meantime, you can use the development version by doing
```
install.packages("remotes")
remotes::install_github("trackerproject/trackeRapp")
library("trackeRapp")
trackeRapp()
```

Let me know if this does not work, or any other issues you spot.

**Comment by handrigg** [comment]
I went through the steps you described to load the development version and I am still encountering the error. I will continue to try on my end and provide an update if I get it working. Thank you for your assistance.

**Comment by ikosmidis** [comment]
Err sorry. I missed an important detail. In a fresh R session try
```
install.packages("remotes")
remotes::install_github("trackerproject/trackeRapp", ref = "develop")
library("trackeRapp")
trackeRapp()
```
before loading trackeRapp. Any luck now?

**Comment by handrigg** [comment]
Success! 

Again, thanks for your assistance and developing/maintaining trackeRapp.
